<template>
  <div class="endattempt-controller">
    <div class="endattempt-controller-progress">
      <div :class="progressClass">
        <div id="msgNotes">{{ progressMessage }}</div>
        <div class="progress">
          <div class="progress-bar" :style="{ width: progressActiveWidth + '%' }" role="progressbar" :aria-valuenow="progressActiveWidth" aria-valuemin="0" aria-valuemax="progressMaximumSteps"></div>
        </div>
      </div>
    </div>
    <div class="endattempt-controller-filler"></div>
    <div class="endattempt-controller-buttons">
      <button v-if="hasTemplates" id="btnNewTemplate" @click.prevent="handleControllerNewTemplate" type="button" class="endattempt-btn endattempt-btn-secondary">New Question</button>
      <button ref="endattempt" id="btnEndAttempt" @click.prevent="handleControllerEndAttempt" type="button" class="endattempt-btn endattempt-btn-primary">{{ title }}</button>
    </div>
  </div>
</template>

<script>
import { store } from '@/store/store'

export default {
  name: 'EndAttemptControllerBar',

  props: {
    responseIdentifier: {
      required: true,
      type: String
    },
    /*
     * The string that should be displayed to the candidate as a prompt for ending the attempt
     * using this interaction. This should be short, preferably one word. A typical value would
     * be "Hint". For example, in a graphical environment it would be presented as the label on
     * a button that, when pressed, ends the attempt.
     */
    title: {
      required: true,
      type: String
    },
    /*
     * Extension point for specifying the max number of steps for an
     * endattempt-controller-bar.
     * String that evaluates to a positive integer (1..n)
     */
    dataSteps: {
      required: false,
      type: String
    },
    /*
     * Extension point for specifying that an endattempt-controller-bar
     * should display a New Question button: { "true" | "false" }
     */
    dataHastemplates: {
      required: false,
      type: String
    },
    /*
     * Extension point for specifying subtypes of an endattempt-controller-bar:
     * { "generic" | "solve" | "showexample" }
     */
    dataControllerType: {
      required: false,
      type: String
    },
    /*
     * Extension point for specifying whether or not to display
     * the endattempt-controller-bar progress panel: { "true" | "false" }
     */
    dataHideprogress: {
      required: false,
      type: String
    }
  },

  data () {
    return {
      // For adaptive items, this permits us to display completion amount
      // in the progress panel.
      step: 1,
      isBtnDisabled: false,
      response: false
    }
  },

  computed: {

    progressMaximumSteps () {
      return (typeof this.dataSteps === 'undefined') ? 1 : (this.dataSteps*1)
    },

    progressActiveWidth () {
      let max = this.progressMaximumSteps
      max = this.step > max ? this.step : max
      return Math.floor(100 * (this.step / max))
    },

    progressMessage () {
      if (this.step === this.progressMaximumSteps) {
        return 'All Parts Showing'
      }
      return 'Step ' + this.step + ' of ' + this.progressMaximumSteps
    },

    hasTemplates () {
      return (typeof this.dataHastemplates !== 'undefined') ? this.dataHastemplates === 'true' : false
    },

    controllerType () {
      return (typeof this.dataControllerType !== 'undefined') ? this.dataControllerType : 'generic'
    },

    progressClass () {
      return {
        'endattempt-progress-panel': true,
        'progress-hidden': (typeof this.dataHideprogress !== 'undefined') ? this.dataHideprogress === 'true' : false
      }
    }

  },

  methods: {

    getStep () {
      return this.step
    },

    setStep (step) {
      // Never let step get bigger than max steps
      this.step = (step < this.progressMaximumSteps ? step : this.progressMaximumSteps)
    },

    incrementStep () {
      this.setStep(this.getStep() + 1)
    },

    getIsBtnDisabled () {
      return this.isBtnDisabled
    },

    setIsBtnDisabled (isBtnDisabled) {
      this.isBtnDisabled = isBtnDisabled
    },

    /**
     * @description Handle the New Template click.
     */
    handleControllerNewTemplate () {
      this.resetControllerState()

      // A new template is generated by the NotifyNewTemplate
      // method in the store.  In turn, this calls a method in
      // the qti-assessment-item component that handles all of
      // the work.
      store.NotifyNewTemplate({
          identifier: this.responseIdentifier,
          step: this.getStep(),
          maximumSteps: this.progressMaximumSteps
        })
    },

    /**
     * @description Handle the end attempt click.
     */
    handleControllerEndAttempt () {
      this.updateControllerState()

      // The end attempt is handled by the
      // parent of this component.
      this.$parent.$emit('endAttempt', {
          response: this.response
        })
    },

    enable () {
      this.toggleButtonDisabled(false)
    },

    disable () {
      this.toggleButtonDisabled(true)
    },

    toggleButtonDisabled (disable) {
      if (disable)
        this.$refs.endattempt.setAttribute('disabled', '')
      else
        this.$refs.endattempt.removeAttribute('disabled')

      this.setIsBtnDisabled(disable)
    },

    resetControllerState () {
      this.setStep(1)
      this.enable()
      this.$parent.$emit('notifyUpdateState', {})
    },

    updateControllerState () {
      console.log('updateControllerState, controllerType:', this.dataControllerType)
      switch (this.dataControllerType) {
/*
        case 'showexample':
        case 'solve':
          this.incrementStep()
          this.finalizeCheckAnswerState()
          break
          */
        case 'generic':
        default:
          if (this.getStep() < this.progressMaximumSteps) {
            this.response = false
            this.incrementStep()
            this.enable()
          } else {
            this.response = true
            this.disable()
            console.log('controller bar disabling button!')
          }
      }
    }

  },

  created () {
  },

  mounted () {
    // Notify parent that we are ready.
    // Pass ourselves to parent.
    this.$parent.$emit('endAttemptReady', {
        node: this
      })
  }
}
</script>

<style>
.endattempt-controller {
  display: flex;
  justify-content: space-between;
}

.endattempt-controller-progress {
}

.endattempt-controller-buttons {
}

.endattempt-controller-filler {
  flex: 1 1 auto;
}

.endattempt-controller #btnEndAttempt,
.endattempt-controller #btnNewQuestion {
  margin-left: .25rem;
}

.progress {
  width: 160px;
  height: 10px;
  background-color: #bbb;
  border-radius: .25rem;
}

.progress-bar {
  border-radius: .25rem;
}

.endattempt-progress-panel {
  float: left;
  margin-left: 2rem;
  margin-top: -2px;
  line-height: 1.75rem;
  font-weight: normal;
  text-align: center;
}

.endattempt-progress-panel.progress-hidden {
  display: none;
}

.endattempt-btn {
  display: inline-block;
  font-weight: 400;
  color: #505d69;
  text-align: center;
  vertical-align: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  outline: 0!important;
  background-color: transparent;
  border: 1px solid transparent;
  padding: .47rem .75rem;
  font-size: .875rem;
  line-height: 1.5;
  border-radius: 30px;
  -webkit-transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
}

.endattempt-btn-secondary {
  color: var(--ea-button-secondary-color);
  background-color: var(--ea-button-secondary-bgc);
  border-color: var(--ea-button-secondary-bc);
}

.endattempt-btn-secondary:hover {
  filter: var(--ea-button-hover-brightness);
}

.endattempt-btn-secondary:focus {
  color: var(--ea-button-secondary-focus-color);
  background-color: var(--ea-button-secondary-focus-bgc);
  border-color: var(--ea-button-secondary-focus-bc);
  -webkit-box-shadow: var(--choice-control-focus-shadow);
  box-shadow: var(--choice-control-focus-shadow);
}

.endattempt-btn-primary {
  color: #fff;
  background-color: #0d6efd;
  border-color: #0d6efd;
}

.endattempt-btn-primary:hover {
  color: #fff;
  background-color: #1878f7;
  border-color: #0c71f6;
}

.endattempt-btn-primary:focus {
  color: #fff;
  background-color: #1878f7;
  border-color: #0c71f6;
  -webkit-box-shadow: var(--choice-control-focus-shadow);
  box-shadow: var(--choice-control-focus-shadow);
}

.endattempt-btn-primary:disabled {
  color: #fff;
  background-color: #3d8ef8;
  border-color: #3d8ef8;
}

/* ============================================
   Overrides for narrower than iPad in portrait
   ============================================ */
@media (max-width:767px) {

  .endattempt-progress-panel {
    margin-left: 0;
  }

  .progress {
    width: 120px;
  }

  .endattempt-btn {
    padding: .47rem .25rem;
    font-size: .875rem;
    border-radius: 30px;
  }

}
</style>
